---
name: UHF Server
version: 0.1.0
slug: uhf_addon
description: Run UHF Server as a Home Assistant add-on
url: https://github.com/YannickSki/home-assistant-uhf-addon
arch:
  - armv7
  - armhf
  - aarch64
init: false
ingress: false
panel_admin: false
apparmor: true
legacy: true
map:
  - config:rw
  - share:rw
ports:
  8000/tcp: 8000
host_network: true
